# Generated by Django 5.1.7 on 2025-04-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
