# Generated by Django 5.1.7 on 2025-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_templates', '0002_alter_articulo_options_articulo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='promocion',
            field=models.BooleanField(default=False),
        ),
    ]
