# Generated by Django 5.1.7 on 2025-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_templates', '0003_articulo_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
