# Generated by Django 5.1.7 on 2025-04-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_templates', '0003_articulo_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leyenda', models.TextField()),
                ('fecha', models.DateField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_templates.articulo')),
            ],
        ),
    ]
